#!/bin/bash

take_ss() {
	
	cd ~/Pictures/Captured/ && scrot 'GabrielDesktop_%Y_%m_%d_%k-%M-%S-$wx$h.png' -q 100  "$1"

}

notify_send() {
	notify-send --expire-time=2000 -i view-fullscreen 'Cheese!~' 'Saved to ~/Pictures/Captured !' --icon='/home/gabriel/Pictures/others/Gabriel Dropout/satania_reindeer.png' && sleep 0.5
}

main() {
	case "$1" in
		crop)
			take_ss -s
			notify_send
			;;
		*)
			notify_send
			take_ss
	esac
}

main "$@"

