#!/usr/bin/sudo bash
trap 'ctrlcdetect' 0 1 2 3 6 9 14 15
ctrlcdetect(){
	clear
	echo " --- --- --- "
	echo "CTRL + C detected"
	echo "nameserver 127.0.0.53" > /etc/resolv.conf
	echo "dns-resolv restored to original."
	echo " Bye!..	"
	echo $othermsg
	echo " --- --- ---"
}

detectonload(){
	if pgrep -x "dnscrypt-proxy" > /dev/null
	then
  	othermsg="dnscrypt already running."
	
	else
    clear
	fi
}
# --

detectonload
echo "		Gabriel = DnsCrypt	"
echo ""
killall dnscrypt-proxy
echo " > execute dnscrypt"
echo "nameserver 127.0.0.1" > /etc/resolv.conf
sudo dnscrypt-proxy -R cisco 

#sudo dnscrypt-proxy /usr/local/etc/dnscrypt-proxy.conf
# -- Gabriel White Tenma -- #
